Repository KentonMewling/Psych-Bot, pull requests merged in 2022-02, with the labels that each got.

#15 finished bot
  .gitignore
  bot.py
  data.json
  requirements.txt
Labels: enhancement

#13 added initial README.md
  README.md
Labels: documentation

#20 Bot Indentation PR Fix
  bot.py
Labels: enhancement

#16 Gantt Chart
  docs/Gantt Chart.png
Labels: documentation

#17 WBS chart added
  docs/WBS.png
Labels: documentation

#21 Updated README.md documentation
  README.md
  bot.py
  docs/images/Demo1.png
  docs/images/Demo2.png
Labels: documentation

#23 Project Plan PR
  docs/Assignment 2 Project Plan.pdf
Labels: documentation

#24 Project Plan Update PR
  docs/Assignment 2 Project Plan.pdf
Labels: documentation, enhancement

#26 Dialog Update
  docs/310.pdf
Labels: documentation

#27 Refactored Code
  .gitignore
  bot.py
  data.json
  docs/Assignment 2 Project Plan.pdf
  docs/Gantt Chart.png
  docs/Script.docx
  docs/WBS.png
  docs/images/Demo1.png
  docs/images/Demo2.png
Labels: documentation, enhancement

#28 Update README.md
  README.md
Labels: documentation

#29 Update Project Plan
  docs/Assignment2_Project_Plan.pdf
Labels: documentation, enhancement
